ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'DATE_INVITE';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'EVENT_CONFIRM';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'EVENT_CANCEL';

ALTER TABLE "Event"
ALTER COLUMN "eventType" TYPE TEXT
USING "eventType"::TEXT;

DROP TYPE "Type";

CREATE TYPE "Type" AS ENUM (
  'SINGLES_MIXER',
  'SPEED_DATES',
  'SINGLES_NIGHT',
  'DINNER_DATES',
  'ACTIVITY_MATCH',
  'PLAY_AND_MATCH',
  'TRAVEL_DATES',
  'TREK_DATES',
  'THE_RESERVE',
  'PROFESSIONALS_MEET',
  'OTHER_DATES'
);

ALTER TABLE "Event"
ALTER COLUMN "eventType" TYPE "Type"
USING "eventType"::TEXT::"Type";

ALTER TABLE "ChatMessage"
ADD COLUMN "eventId" UUID;

ALTER TABLE "ChatMessage"
ADD CONSTRAINT "ChatMessage_eventId_fkey"
FOREIGN KEY ("eventId")
REFERENCES "Event"("id")
ON DELETE SET NULL
ON UPDATE CASCADE;